# Generated by scripts/vendor_lib.py from src/godox_mesh_bt/sequence.py
# Do not edit directly; edit the source module and re-run the script.
"""Crash-safe reservation of Bluetooth Mesh sequence numbers.

A mesh node keeps a replay protection list and silently drops any PDU whose
sequence number it has already seen. A long-running controller therefore must
never reissue a number after a restart — but persisting to disk on every single
command is wasteful when commands arrive as fast as a dimmer slider moves.

:class:`SequenceReserver` claims a block of numbers up front, persists only the
block boundary, then serves the block from memory. A crash loses at most the
unused tail of the block, which is harmless: the next process resumes above it.

Examples
--------
>>> persisted = []
>>> reserver = SequenceReserver(100, block_size=50, persist=persisted.append)
>>> reserver.take()
100
>>> persisted
[150]
"""

from __future__ import annotations

import logging
from collections.abc import Callable

logger = logging.getLogger(__name__)

DEFAULT_BLOCK_SIZE = 256


class SequenceReserver:
    """Serve mesh sequence numbers from a durably reserved block.

    Parameters
    ----------
    start
        Sequence number to resume from, usually the persisted high-water mark
        left behind by a previous process.
    block_size
        How many sequence numbers to claim per persistence write. Larger blocks
        mean fewer writes and a larger gap after an unclean shutdown.
    persist
        Callback invoked with a new high-water mark whenever a block is claimed.
        It must durably record the value before the block is used on air.

    Examples
    --------
    >>> reserver = SequenceReserver(0, block_size=2, persist=lambda value: None)
    >>> [reserver.take() for _ in range(3)]
    [0, 1, 2]
    """

    def __init__(
        self,
        start: int,
        *,
        block_size: int = DEFAULT_BLOCK_SIZE,
        persist: Callable[[int], None],
    ) -> None:
        if block_size <= 0:
            raise ValueError("block_size must be positive")
        if start < 0:
            raise ValueError("start must be non-negative")
        self._next = start
        self._block_size = block_size
        self._persist = persist
        self._high_water_mark = start

    @property
    def high_water_mark(self) -> int:
        """Return the highest sequence number handed to :attr:`persist`.

        Returns
        -------
        int
            Upper bound of the currently reserved block. Every number below it
            is considered spent, whether or not it was actually transmitted.

        Examples
        --------
        >>> reserver = SequenceReserver(10, block_size=5, persist=lambda value: None)
        >>> reserver.high_water_mark
        10
        """

        return self._high_water_mark

    def take(self) -> int:
        """Return the next sequence number, claiming a new block if needed.

        Returns
        -------
        int
            A sequence number that no previous process can have used.

        Examples
        --------
        >>> reserver = SequenceReserver(7, block_size=4, persist=lambda value: None)
        >>> reserver.take()
        7
        """

        if self._next >= self._high_water_mark:
            self._reserve(self._next)
        value = self._next
        self._next += 1
        return value

    def observe(self, used: int) -> None:
        """Record a sequence number consumed by a counter owned elsewhere.

        Use this when another object — such as :class:`GodoxController` — owns
        the running counter and this reserver only decides when the value must
        be written to durable storage.

        Parameters
        ----------
        used
            Sequence number that has just been sent on air.

        Returns
        -------
        None
            A fresh block is persisted whenever ``used`` reaches the current
            high-water mark, so the stored value always stays ahead of the
            counter.

        Examples
        --------
        >>> persisted = []
        >>> reserver = SequenceReserver(0, block_size=4, persist=persisted.append)
        >>> reserver.observe(4)
        >>> persisted
        [8]
        """

        self._next = max(self._next, used + 1)
        if used >= self._high_water_mark:
            self._reserve(used)

    def _reserve(self, floor: int) -> None:
        # Align to block boundaries so the mark advances predictably no matter
        # whether numbers are pulled through take() or observed after the fact.
        self._high_water_mark = (floor // self._block_size + 1) * self._block_size
        logger.debug(
            "reserving mesh sequence numbers through %d",
            self._high_water_mark - 1,
        )
        self._persist(self._high_water_mark)
