"""Vendor the mesh library into the Home Assistant integration.

Home Assistant installs an integration's ``requirements`` from PyPI. Rather
than tie this fork's integration to a published release of the library it sits
next to, the library is copied into the integration and imported from there.

The copy is generated, never hand-edited: run this script after changing
anything under ``src/godox_mesh_bt`` and commit the result.
``tests_ha/test_vendored_lib.py`` fails if the two drift apart.

Usage
-----
    uv run python scripts/vendor_lib.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = REPO_ROOT / "src" / "godox_mesh_bt"
VENDOR_DIR = REPO_ROOT / "custom_components" / "godox_mesh" / "_lib"

# The transitive closure of what the integration imports. The command line
# entry points, the interactive scanner and the GATT inspector are all CLI-only
# and would drag in dependencies the integration has no use for.
MODULES = (
    "__init__",
    "client",
    "config",
    "config_session",
    "controller",
    "crypto",
    "protocol",
    "provisioning",
    "provisioning_client",
    "provisioning_pdu",
    "sequence",
    "state",
)

HEADER = (
    "# Generated by scripts/vendor_lib.py from src/godox_mesh_bt/{name}.py\n"
    "# Do not edit directly; edit the source module and re-run the script.\n"
)


def rewrite_imports(source: str) -> str:
    """Turn the package's absolute self-imports into relative ones.

    The vendored copy lives at ``custom_components.godox_mesh._lib``, so
    ``from godox_mesh_bt.client import X`` would look outside the
    integration and pick up an installed copy — or fail.
    """
    source = re.sub(
        r"^from godox_mesh_bt\.([\w.]+) import ",
        r"from .\1 import ",
        source,
        flags=re.MULTILINE,
    )
    source = re.sub(
        r"^from godox_mesh_bt import ",
        "from . import ",
        source,
        flags=re.MULTILINE,
    )
    return re.sub(
        r"^import godox_mesh_bt\.([\w.]+)$",
        r"from . import \1",
        source,
        flags=re.MULTILINE,
    )


def build() -> dict[str, str]:
    """Return the vendored file contents keyed by file name."""
    files = {}
    for name in MODULES:
        source = (SOURCE_DIR / f"{name}.py").read_text()
        files[f"{name}.py"] = HEADER.format(name=name) + rewrite_imports(source)
    return files


def main() -> int:
    """Write the vendored copy, replacing whatever is there."""
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    for stale in VENDOR_DIR.glob("*.py"):
        stale.unlink()
    files = build()
    for name, content in files.items():
        (VENDOR_DIR / name).write_text(content)
    print(f"vendored {len(files)} modules into {VENDOR_DIR.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
